#!/bin/bash
#SBATCH --job-name=cia_4ds_1k
#SBATCH --array=1-72%20
#SBATCH --partition=gpu,hugheslab
#SBATCH --qos=preempt
#SBATCH --gres=gpu:1
#SBATCH --mem=16g
#SBATCH --ntasks=4
#SBATCH --time=16:00:00
#SBATCH --error=/cluster/tufts/hugheslab/zmou01/slurmlog/err/log_%A_%a.err
#SBATCH --output=/cluster/tufts/hugheslab/zmou01/slurmlog/out/log_%A_%a.out

source ~/.bashrc
conda activate /cluster/tufts/hugheslab/zmou01/conda_envs/neuroimg_gpu
cd /cluster/home/zmou01/pooling

# CIA re-run at 1000 epochs (was 600), to match the notebook epoch budget.
experiments=(
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=1001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=1001 --data_seed_val=1002 --data_seed_test=1003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=3001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=3001 --data_seed_val=3002 --data_seed_test=3003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=1001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=1001 --data_seed_val=1002 --data_seed_test=1003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=3001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=3001 --data_seed_val=3002 --data_seed_test=3003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=1001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=1001 --data_seed_val=1002 --data_seed_test=1003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=3001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=3001 --data_seed_val=3002 --data_seed_test=3003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=1001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=1001 --data_seed_val=1002 --data_seed_test=1003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=3001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=3001 --data_seed_val=3002 --data_seed_test=3003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=1001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=1001 --data_seed_val=1002 --data_seed_test=1003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=3001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=3001 --data_seed_val=3002 --data_seed_test=3003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=1001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=1001 --data_seed_val=1002 --data_seed_test=1003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=3001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=3001 --data_seed_val=3002 --data_seed_test=3003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_noL1_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.2 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=0.8 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --alpha=0.0 --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --beta_effect=1.0 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_embedding_level=True" --model_name="alpha=0.0_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=3001"'
)

cmd="${experiments[$SLURM_ARRAY_TASK_ID - 1]}"
exp=$(sed -E 's/.*--experiments_dir="([^"]+)".*/\1/' <<<"$cmd")
mn=$(sed -E 's/.*--model_name="([^"]+)".*/\1/' <<<"$cmd")
if [ -f "$exp/$mn.pt" ] && [ "$(wc -l < "$exp/$mn.csv" 2>/dev/null || echo 0)" -ge 1001 ]; then echo "already done: $mn"; exit 0; fi
sleep $(( (RANDOM % 40) + SLURM_ARRAY_TASK_ID % 15 ))
for attempt in 1 2 3 4 5; do eval "$cmd" && break; echo "attempt $attempt failed, backoff" >&2; sleep $(( attempt*45 + RANDOM%30 )); done
