#!/bin/bash
#SBATCH --job-name=cia_l1_retry
#SBATCH --array=1-26%8
#SBATCH --partition=gpu,hugheslab
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --mem=16g
#SBATCH --ntasks=4
#SBATCH --time=14:00:00
#SBATCH --error=/cluster/tufts/hugheslab/zmou01/slurmlog/err/log_%A_%a.err
#SBATCH --output=/cluster/tufts/hugheslab/zmou01/slurmlog/out/log_%A_%a.out

source ~/.bashrc
conda activate /cluster/tufts/hugheslab/zmou01/conda_envs/neuroimg_gpu
cd /cluster/home/zmou01/pooling

# Retry for the 26/216 CIA+L1 1000-epoch tasks that silently failed on 3552505
# (all 5 attempts hit "CUDA-capable device(s) is/are busy", but the old wrapper
# didn't propagate the failure so the array task still reported COMPLETED).
# qos=normal avoids the preempt-QOS device-busy storm; this version also exits
# non-zero on total failure so SLURM/sacct reflects reality.
experiments=(
    'python src/synthetic_data.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=0.2 --lr=0.01 --seed=1001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=1001 --data_seed_val=1002 --data_seed_test=1003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/synthetic_data.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=0.2 --lr=0.001 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=0.8 --lr=0.01 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=1e-05 --beta_effect=0.2 --lr=0.01 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_L1_embedding_level=True" --model_name="alpha=1e-05_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=1e-05 --beta_effect=0.2 --lr=0.001 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_L1_embedding_level=True" --model_name="alpha=1e-05_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/synthetic_data.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=1e-05 --beta_effect=1.0 --lr=0.001 --seed=2001 --delta=0.5 --r=12 --n_train=10000 --n_val=2500 --n_test=1000 --data_seed_train=2001 --data_seed_val=2002 --data_seed_test=2003 --experiments_dir="/cluster/home/zmou01/pooling/experiments/synthetic_CIA_L1_embedding_level=True" --model_name="alpha=1e-05_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.001 --beta_effect=0.2 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_CIA_L1_embedding_level=True" --model_name="alpha=0.001_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.001 --beta_effect=0.8 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_CIA_L1_embedding_level=True" --model_name="alpha=0.001_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=0.2 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=0.2_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=0.8 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=1.0 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=1e-05 --beta_effect=0.8 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_CIA_L1_embedding_level=True" --model_name="alpha=1e-05_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=1e-05 --beta_effect=1.0 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_CIA_L1_embedding_level=True" --model_name="alpha=1e-05_criterion=CIA_beta_effect=1.0_lr=0.001_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.001 --beta_effect=0.8 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_L1_embedding_level=True" --model_name="alpha=0.001_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.001 --beta_effect=1.0 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_L1_embedding_level=True" --model_name="alpha=0.001_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=0.8 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=0.8 --lr=0.001 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=1e-05 --beta_effect=0.2 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_L1_embedding_level=True" --model_name="alpha=1e-05_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=1e-05 --beta_effect=1.0 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_PE/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_PE_CIA_L1_embedding_level=True" --model_name="alpha=1e-05_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.001 --beta_effect=0.2 --lr=0.01 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_L1_embedding_level=True" --model_name="alpha=0.001_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=3001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.001 --beta_effect=0.8 --lr=0.001 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_L1_embedding_level=True" --model_name="alpha=0.001_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.001 --beta_effect=1.0 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_L1_embedding_level=True" --model_name="alpha=0.001_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=0.8 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=0.8_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=0.0001 --beta_effect=1.0 --lr=0.01 --seed=2001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=2001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_L1_embedding_level=True" --model_name="alpha=0.0001_criterion=CIA_beta_effect=1.0_lr=0.01_pooling=ABMIL_seed=2001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=1e-05 --beta_effect=0.2 --lr=0.01 --seed=1001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=1001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_L1_embedding_level=True" --model_name="alpha=1e-05_criterion=CIA_beta_effect=0.2_lr=0.01_pooling=ABMIL_seed=1001"'
    'python src/oasis-3.py --batch_size=64 --criterion="CIA" --epochs=1000 --embedding_level --pooling="ABMIL" --save --weight_decay=0.0 --alpha=1e-05 --beta_effect=0.8 --lr=0.001 --seed=3001 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_AT/ViT_B_16/seed=3001" --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_AT_CIA_L1_embedding_level=True" --model_name="alpha=1e-05_criterion=CIA_beta_effect=0.8_lr=0.001_pooling=ABMIL_seed=3001"'
)

cmd="${experiments[$SLURM_ARRAY_TASK_ID - 1]}"
exp=$(sed -E 's/.*--experiments_dir="([^"]+)".*/\1/' <<<"$cmd")
mn=$(sed -E 's/.*--model_name="([^"]+)".*/\1/' <<<"$cmd")
if [ -f "$exp/$mn.pt" ] && [ "$(wc -l < "$exp/$mn.csv" 2>/dev/null || echo 0)" -ge 1001 ]; then echo "already done: $mn"; exit 0; fi
sleep $(( (RANDOM % 40) + SLURM_ARRAY_TASK_ID % 15 ))
ok=0
for attempt in 1 2 3 4 5; do
  eval "$cmd" && { ok=1; break; }
  echo "attempt $attempt failed, backoff" >&2
  sleep $(( attempt*45 + RANDOM%30 ))
done
[ "$ok" = "1" ] || { echo "ALL ATTEMPTS FAILED: $mn" >&2; exit 1; }
