#!/bin/bash
#SBATCH --job-name=ng_fkl_1k
#SBATCH --array=1-108%20
#SBATCH --partition=gpu,hugheslab
#SBATCH --qos=preempt
#SBATCH --gres=gpu:1
#SBATCH --mem=16g
#SBATCH --ntasks=4
#SBATCH --time=14:00:00
#SBATCH --error=/cluster/tufts/hugheslab/zmou01/slurmlog/err/log_%A_%a.err
#SBATCH --output=/cluster/tufts/hugheslab/zmou01/slurmlog/out/log_%A_%a.out

source ~/.bashrc
conda activate /cluster/tufts/hugheslab/zmou01/conda_envs/neuroimg_gpu
cd /cluster/home/zmou01/pooling

# NG forward-KL alpha x lr sweep, re-run at the notebook-matching 1000 epochs (was 600).
experiments=(
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=full_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=full_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=full_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=full_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=full_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=full_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=centered_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=centered_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.1 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=centered_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.01 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=1e-05 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=1000 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_fkl_sweep_embedding_level=True" --lr=0.001 --model_name="alpha=1e-05_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
)

cmd="${experiments[$SLURM_ARRAY_TASK_ID - 1]}"
exp=$(sed -E 's/.*--experiments_dir="([^"]+)".*/\1/' <<<"$cmd")
mn=$(sed -E 's/.*--model_name="([^"]+)".*/\1/' <<<"$cmd")
if [ -f "$exp/$mn.pt" ] && [ "$(wc -l < "$exp/$mn.csv" 2>/dev/null || echo 0)" -ge 1001 ]; then echo "already done: $mn"; exit 0; fi
sleep $(( (RANDOM % 40) + SLURM_ARRAY_TASK_ID % 15 ))
for attempt in 1 2 3 4 5; do eval "$cmd" && break; echo "attempt $attempt failed, backoff" >&2; sleep $(( attempt*45 + RANDOM%30 )); done
