#!/bin/bash
#SBATCH --job-name=ich_ng_kl
#SBATCH --array=1-24%12
#SBATCH --partition=gpu,hugheslab
#SBATCH --gres=gpu:1
#SBATCH --mem=16g
#SBATCH --ntasks=4
#SBATCH --time=08:00:00
#SBATCH --error=/cluster/tufts/hugheslab/zmou01/slurmlog/err/log_%A_%a.err
#SBATCH --output=/cluster/tufts/hugheslab/zmou01/slurmlog/out/log_%A_%a.out

source ~/.bashrc
conda activate /cluster/tufts/hugheslab/zmou01/conda_envs/neuroimg_gpu
cd /cluster/home/zmou01/pooling

# NG mean/variance ablation, forward-KL and reverse-KL divergence, RSNA ICH ABMIL.
# Fixed hparams (notebook headline NG-ABMIL selection): alpha=1e-4, beta(lambda)=1.0,
# lr = 0.01/0.01/0.001 for seed 1001/2001/3001. ng_mode in {full,fit_mean,fit_std,centered}.
experiments=(
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=full_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="forward kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=fkl_ng=centered_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=full_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=full_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=full_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=fit_std_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=fit_std_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=centered_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=centered_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --divergence="reverse kl" --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_KL_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_div=rkl_ng=centered_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
)

eval "${experiments[$SLURM_ARRAY_TASK_ID - 1]}"
