#!/bin/bash
#SBATCH --job-name=ich_ng_abl
#SBATCH --array=1-36%16
#SBATCH --partition=hugheslab
#SBATCH --gres=gpu:1
#SBATCH --mem=16g
#SBATCH --ntasks=4
#SBATCH --time=08:00:00
#SBATCH --error=/cluster/tufts/hugheslab/zmou01/slurmlog/err/log_%A_%a.err
#SBATCH --output=/cluster/tufts/hugheslab/zmou01/slurmlog/out/log_%A_%a.out

source ~/.bashrc
conda activate /cluster/tufts/hugheslab/zmou01/conda_envs/neuroimg_gpu
cd /cluster/home/zmou01/pooling

# NG mean/variance ablation on RSNA ICH (head CT), ABMIL, criterion=GuidedL1, beta(lambda)=1.0, alpha=1e-4.
#   full     = fit both moments from attention (standard Normal Guidance)
#   fit_mean = fit center from attention, freeze std to empirical (0.115 * S_i)
#   fit_std  = freeze center to empirical (0.52 * S_i), fit std from attention
#   centered = freeze both to empirical (the centered-prior baseline)
# empirical_mean/std computed from training-set positive-slice normalized positions.
experiments=(
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=full_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=full_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=full_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=full_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=full_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=full_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=full_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=full_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=full_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=full --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_mean_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_mean_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_mean_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_mean --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_std_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_std_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_std_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_std_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_std_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_std_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_std_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_std_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=fit_std_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=fit_std --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=centered_lr=0.1_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=centered_lr=0.1_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.1 --model_name="alpha=0.0001_criterion=GuidedL1_ng=centered_lr=0.1_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=centered_lr=0.01_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=centered_lr=0.01_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.01 --model_name="alpha=0.0001_criterion=GuidedL1_ng=centered_lr=0.01_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=1001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=centered_lr=0.001_pooling=ABMIL_seed=1001" --pooling="ABMIL" --save --seed=1001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=2001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=centered_lr=0.001_pooling=ABMIL_seed=2001" --pooling="ABMIL" --save --seed=2001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
    'python src/oasis-3.py --alpha=0.0001 --batch_size=64 --criterion="GuidedL1" --beta=1.0 --dataset_dir="/cluster/tufts/hugheslab/datasets/encoded_RSNA_ICH_full_dataset/ViT_B_16/seed=3001" --epochs=400 --embedding_level --experiments_dir="/cluster/home/zmou01/pooling/experiments/RSNA_ICH_full_dataset_NG_variance_ablation_embedding_level=True" --lr=0.001 --model_name="alpha=0.0001_criterion=GuidedL1_ng=centered_lr=0.001_pooling=ABMIL_seed=3001" --pooling="ABMIL" --save --seed=3001 --weight_decay=0.0 --ng_mode=centered --empirical_mean=0.52 --empirical_std=0.115'
)

eval "${experiments[$SLURM_ARRAY_TASK_ID - 1]}"
