#!/bin/bash
#SBATCH --array=0-59%6
#SBATCH --error=/cluster/tufts/hugheslab/dloevl01/slurmlog/err/log_%j.err
#SBATCH --gres=gpu:rtx_a6000:1
#SBATCH --mem=16g
#SBATCH --ntasks=4
#SBATCH --output=/cluster/tufts/hugheslab/dloevl01/slurmlog/out/log_%j.out
#SBATCH --partition=hugheslab
#SBATCH --time=120:00:00

source ~/.bashrc
conda activate jupyter-env

# Timing experiments: 5 methods x 3 seeds x 2 alphas x 2 lrs = 60 experiments
# Using 6 parallel jobs (%6) on 8 available GPUs
experiments=(
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=Max_seed=1001_timing' --pooling='Max' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=Max_seed=2001_timing' --pooling='Max' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=Max_seed=3001_timing' --pooling='Max' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=Max_seed=1001_timing' --pooling='Max' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=Max_seed=2001_timing' --pooling='Max' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=Max_seed=3001_timing' --pooling='Max' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=Max_seed=1001_timing' --pooling='Max' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=Max_seed=2001_timing' --pooling='Max' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=Max_seed=3001_timing' --pooling='Max' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=Max_seed=1001_timing' --pooling='Max' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=Max_seed=2001_timing' --pooling='Max' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=Max_seed=3001_timing' --pooling='Max' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=Mean_seed=1001_timing' --pooling='Mean' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=Mean_seed=2001_timing' --pooling='Mean' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=Mean_seed=3001_timing' --pooling='Mean' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=Mean_seed=1001_timing' --pooling='Mean' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=Mean_seed=2001_timing' --pooling='Mean' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=Mean_seed=3001_timing' --pooling='Mean' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=Mean_seed=1001_timing' --pooling='Mean' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=Mean_seed=2001_timing' --pooling='Mean' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=Mean_seed=3001_timing' --pooling='Mean' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=Mean_seed=1001_timing' --pooling='Mean' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=Mean_seed=2001_timing' --pooling='Mean' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=Mean_seed=3001_timing' --pooling='Mean' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=ABMIL_seed=1001_timing' --pooling='ABMIL' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=ABMIL_seed=2001_timing' --pooling='ABMIL' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=ABMIL_seed=3001_timing' --pooling='ABMIL' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=ABMIL_seed=1001_timing' --pooling='ABMIL' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=ABMIL_seed=2001_timing' --pooling='ABMIL' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=ABMIL_seed=3001_timing' --pooling='ABMIL' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=ABMIL_seed=1001_timing' --pooling='ABMIL' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=ABMIL_seed=2001_timing' --pooling='ABMIL' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=ABMIL_seed=3001_timing' --pooling='ABMIL' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=ABMIL_seed=1001_timing' --pooling='ABMIL' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=ABMIL_seed=2001_timing' --pooling='ABMIL' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=ABMIL_seed=3001_timing' --pooling='ABMIL' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=TransMIL_seed=1001_timing' --pooling='TransMIL' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=TransMIL_seed=2001_timing' --pooling='TransMIL' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=TransMIL_seed=3001_timing' --pooling='TransMIL' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=TransMIL_seed=1001_timing' --pooling='TransMIL' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=TransMIL_seed=2001_timing' --pooling='TransMIL' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=TransMIL_seed=3001_timing' --pooling='TransMIL' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=TransMIL_seed=1001_timing' --pooling='TransMIL' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=TransMIL_seed=2001_timing' --pooling='TransMIL' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=TransMIL_seed=3001_timing' --pooling='TransMIL' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=TransMIL_seed=1001_timing' --pooling='TransMIL' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=TransMIL_seed=2001_timing' --pooling='TransMIL' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=TransMIL_seed=3001_timing' --pooling='TransMIL' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=SmAP_seed=1001_timing' --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=SmAP_seed=2001_timing' --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=0.0_lr=0.01_pooling=SmAP_seed=3001_timing' --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=SmAP_seed=1001_timing' --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=SmAP_seed=2001_timing' --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=0.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=0.0_lr=0.0001_pooling=SmAP_seed=3001_timing' --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=SmAP_seed=1001_timing' --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=SmAP_seed=2001_timing' --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.01 --model_name='alpha=1.0_lr=0.01_pooling=SmAP_seed=3001_timing' --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=1001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=SmAP_seed=1001_timing' --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=2001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=SmAP_seed=2001_timing' --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/oasis-3-timing.py --alpha=1.0 --batch_size=64 --criterion='L1' --dataset_dir='/cluster/tufts/hugheslab/dloevl01/encoded_RSNA/ViT_B_16/seed=3001' --embedding_level --epochs=1000 --experiments_dir='/cluster/tufts/hugheslab/dloevl01/pooling/experiments/RSNA/timing' --lr=0.0001 --model_name='alpha=1.0_lr=0.0001_pooling=SmAP_seed=3001_timing' --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
)

# Run the experiment corresponding to SLURM_ARRAY_TASK_ID
eval ${experiments[$SLURM_ARRAY_TASK_ID]}
